### ISSUE TITLE
Improve definition of LPP loading

### ISSUE THREAD

**Issue by gonuke** [makeclean/itersdr-report#19]
currently refer to it as "unplugged" - is there a better operational word?

**Comment by makeclean** [comment]
There is a PCR in to address the issue of the open pumping duct to add some shielding. But our model does not include this.

**Comment by gonuke** [comment]
We should change the text to declare the state of this port in the model in the affirmative rather than the negative.  We don't care what it isn't but just what it is.  Did one of Ahmad's emails clarify this?

**Comment by gonuke** [comment]
LPP contains a cryopump.  This component is already known to provide inadequate shielding but is still the reference design.

**Comment by gonuke** [comment]
Closed by #29
