### ISSUE TITLE
Generate SDR lineout plots

### ISSUE THREAD

**Issue by gonuke** [makeclean/itersdr-report#4]
- [x] EPP lineouts for 3 decay times
- [x] UPP lineouts at bottom of flange for 3 decay times
- [x] UPP lineouts at top of flange for 3 decay times

**Comment by makeclean** [comment]
PR Incoming

**Comment by gonuke** [comment]
Will this PR also place these plots in the document?

**Comment by makeclean** [comment]
Yes it will

**Comment by makeclean** [comment]
I can always put them in, in one pr then make another for the text?
